<s> personal wealth : will privatization improve private wealth ? <eos>

<s> we all know that the social security system is severely underfunded ; it 's headed for bankruptcy sometime in the # s. implementing private accounts will take # percent of the # . # percent taxes from every worker out of the trust fund . thus almost a # rd of the revenue generated by social security taxes will be removed . drastic benefit cuts or increased taxes will have to occur even sooner which is a recipe for disaster . <eos>

@highlight

<s> privatized social security will cut tax revenues and social services . <eos>

