<s> free speech : does unlimited spending uphold free speech ? <eos>

<s> citizens united vs. federal election commission # - # majority opinion of the court : `` the concurrence explained that any 'undue influence ' generated by a speaker s 'large expen-ditures ' was outweighed 'by the loss for democratic proc-esses resulting from the restrictions upon free and fullpublic discussion . ' id . at # . [ ... ] in united states v. automobile workers # u. s. # ( # ) [ ... ] the dissent concluded that deeming a particular group too powerful was not a 'justificatio [ n ] for withholdingfirst amendment rights from any group labor or corpo-rate . ' id . at # . '' <eos>

@highlight

<s> free speech more important than fighting corporate interests <eos>

