<s> abuse : would legal prostitution experience less violence ? <eos>

<s> the legalization of the bunny ranch in nevada did not prevent the majority of prostitutes from continuing to work outside of the licensed brothel and remain dependent on pimps . this is because brothels are more expensive environments for prostitutes to work and clients to visit . rent health checks and security are some of the costs which make it uneconomic for some prostitutes to be employed in brothels . in britain where prostitution is virtually prohibited some prostitutes use private apartments whilst others work on the street . legalisation of prostitution does not remove the street market or the dangers associated with it . the dangerous street environment is generated by simple economics not legal controls . <eos>

@highlight

<s> legalization does not ensure that prostitutes wo n't continue to work with `` pimps '' . <eos>

