<s> own wealth : will privatization improving public wealth ? <eos>

<s> we all know that the social secure system is severely underfunded ; it 's headed for bankruptcy sometime in the # s. implementing private accounts will take # percent of the # . # percent taxes from every worker out of the trust fund . thus almost a # rd of the revenues generated by social secure taxes will be removed . drastic benefits cuts or increased taxes will have to occur even sooner which is a pie for disaster . <eos>

@highlight

<s> privatize social security will cut tax revenues and social services . <eos>

