<s> civilian threat : does chinese representing a growing civilian threat ? <eos>

<s> in terms of defense spending china is insignificant accounting for only # . # % of the global total as opposed to # . # % generated by the us . similarly the amount of arm dealing is also no causes for concern . china transferred $ # billion of weapons constituting # . # % of the global total . the united states by contrasts traded # % of the world s weapons and britain # % . moreover it could hardly be claiming that these powers themselves have an ethical record for the manufacturing and sale of weapons . british fighter planes have been used in the suppressing of civil unrest in indonesia and east timor whilst american weapons have equipped the taleban in afghanistan and the khmer rouge in cambodia . the us has refused <eos>

@highlight

<s> people wrongly associate a military threat with the communist politics regime rather than the pacific attitudes of its leaders : <eos>

