<s> civilian threat : does china representing a growing civilian threat ? <eos>

<s> in terms of defence spending china is insignificant audit for only # . # % of the global total as opposed to # . # % generated by the us . equally the amount of arms dealing is also no cause for concern . china transferred $ # billion of weapon constituting # . # % of the global total . the united states by contrast traded # % of the world s weapon and britain # % . moreover it could hardly be claiming that these powers themselves have an ethical record for the manufacture and sale of weapons . british fighter planes have been used in the suppression of civil unrest in indonesia and east timor whilst american weapon have equipped the talibans in afghanistan and the khmer rouge in cambodia . the us has refused <eos>

@highlight

<s> people erroneously associate a military threat with the communist political regime perhaps than the pacific attitudes of its leaders : <eos>

