<s> competition : is the competition introduced by vouchers a good thing ? <eos>

<s> public schools are unlikely to be able to respond to increased competitive pressure generated by vouchers . [ 2 ] this is not the fault of public schools - they are not designed to `` compete '' . public schools are designed to provide an education that reflects the educational priorities of a society ; this is not something that competition can necessarily foster . private schools often have a very different mission and are designed to compete in some case purely for profit . it is wrong to attempt to mix non-competitive public schools and competitive private schools in a competitive voucher system . obviously public schools will lose undermining the common values driving the public education system . <eos>

@highlight

<s> vouchers damage public schools that ca n't compete with private schools . <eos>

