<s> abuse : would legal prostitutes experience than violence ? <eos>

<s> the legalization of the bunny ranch in nevada did not prevent the majority of prostitutes from continuing to work outside of the licensed brothels and remain dependent on pimps . this is because brothel are more expensive environments for prostitutes to work and clients to visit . rent health checking and security are some of the costs which make it uneconomic for some prostitutes to be employed in brothels . in britain where prostitution is virtually prohibited some prostitutes use public apartments whilst others work on the street . legalization of prostitution does not remove the street market or the dangers associated with it . the dangerous street environments is generated by simple economics not legal controls . <eos>

@highlight

<s> legalization does not ensure that prostitute wo n't continue to work with `` pimps '' . <eos>

