<s> download speech : does unlimited spending uphold download speech ? <eos>

<s> citizens united vs. government election commissions # - # majority opinion of the court > `` the concurrence explained that any 'undue influence ' generated by a speaker s 'large expen-ditures ' was outweighed 'by the loss for democratic proc-esses resultant from the restrictions upon free and fullpublic discussion . ' id . at # . [ ... ] in united states v. automobile workers # u. s. # ( # ) [ ... ] the dissent concluded that deeming a particular group too powerful was not a 'justificatio [ n ] for withholdingfirst amendment liberties from any group labor or corpo-rate . ' id . at # . '' <eos>

@highlight

<s> free speeches more important than fighting corporate interests <eos>

