<s> international security : is chinese a threats to we security ? <eos>

<s> in terms of defence spending china is insignificant accounting for only # . # % of the global total as oppose to # . # % generated by the us . similarly the amount of arms dealing is also no cause for concern . china transferred $ # billion of weapon constituting # . # % of the global total . the united states by contrast traded # % of the world s weapon and britain # % . moreover it would hardly be claimed that these powers themselves have an ethical record for the manufacturing and sale of weapons . british fighter planes have been used in the suppression of civil unrest in indonesia and east timor whilst american weapon have equipped the taleban in afghanistan and the khmer rouge in cambodia . the us has refused <eos>

@highlight

<s> people wrongly associate a military threats with the communist politics regime rather than the pacific attitudes of its leaders : <eos>

